steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--build-arg'
    - 'TAVILY_API_KEY=${TAVILY_API_KEY}'
    - '--build-arg'
    - 'DATABASE_URL=${DATABASE_URL}'
    - '--build-arg'
    - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
    - '--build-arg'
    - 'NEXT_PUBLIC_PROJECT_ID=${NEXT_PUBLIC_PROJECT_ID}'
    - '.'
  secretENV: ['NEXT_PUBLIC_PROJECT_ID', 'OPENAI_API_KEY', 'DATABASE_URL', 'TAVILY_API_KEY']
 
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
    env: 'DATABASE_URL'
  - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_PROJECT_ID/versions/latest
    env: 'NEXT_PUBLIC_PROJECT_ID'
  - versionName: projects/$PROJECT_ID/secrets/OPENAI_API_KEY/versions/latest
    env: 'OPENAI_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/TAVILY_API_KEY/versions/latest
    env: 'TAVILY_API_KEY'
